import type { SkillDef } from "../types";

/**
 * スキルマスターデータ。
 * treeId でスキルツリー画面上の4本のツリーに振り分けられる。
 * id は LayerNodeData.layerType / activation / regularization や
 * playStore.selectedOptimizer と直接対応する。
 */
export const SKILL_DATA: SkillDef[] = [
  // ============ 隠れ層ツリー ============
  {
    id: "dense",
    treeId: "layer",
    name: "全結合層 (Dense)",
    description: "基本的なニューラルネットワークの層。",
    detail: "前の層にあるすべてのノードと次の層にあるすべてのノードがそれぞれ結合している層。分類問題などの最終判断を下すタスクに適しているが、計算コストが高くなりやすく、過学習も起きやすい。入力データは1次元でなければならない。",
    cost: 0,
    dependencies: [],
  },
  {
    id: "dense_width_cap_4",
    treeId: "layer",
    name: "Dense幅 4",
    description: "Dense の幅を 1〜4 まで使えるようにする。",
    detail: "Dense の units を 1〜4 の整数から選べるようにする。",
    cost: 10,
    dependencies: ["dense"],
  },
  {
    id: "model_params_cap_32",
    treeId: "layer",
    name: "総パラメータ上限 32",
    description: "モデル全体で 32 パラメータまで使えるようにする。",
    detail:
      "全層を合計した総パラメータ数の上限を 32 まで許可する。幅だけでなく、層を積んだときの総量も制御する。",
    cost: 0,
    dependencies: ["dense"],
  },
  {
    id: "flatten",
    treeId: "layer",
    name: "Flatten",
    description: "多次元テンソルを1次元に変換する層。",
    detail: "多次元テンソルを1次元に変換することにより、データを後続の処理が受け取れる形に整える層。1次元に変換することで失われる情報に注意が必要。",
    cost: 80,
    dependencies: ["dense"],
  },
  {
    id: "conv2d",
    treeId: "layer",
    name: "畳み込み層 (Conv2D)",
    description: "空間的な特徴を抽出する層。画像系タスクに有効。",
    detail: "画像の局所的なパターンを効率よく抽出する層。少ないパラメータで重要な特徴を取り出すことができ、データの並びを保ったまま処理できるため、画像を扱うタスクで学習が安定しやすい。層を重ねるほど、より複雑な構造を理解できるようになる。",
    cost: 180,
    dependencies: ["flatten"],
  },
  {
    id: "dense_width_cap_6",
    treeId: "layer",
    name: "Dense幅 6",
    description: "Dense の幅を 1〜6 まで使えるようにする。",
    detail: "Dense の units を 1〜6 の整数から選べるようにする。",
    cost: 20,
    dependencies: ["dense_width_cap_4"],
  },
  {
    id: "model_params_cap_64",
    treeId: "layer",
    name: "総パラメータ上限 64",
    description: "モデル全体で 64 パラメータまで使えるようにする。",
    detail: "総パラメータ上限を 64 まで拡張する。",
    cost: 15,
    dependencies: ["model_params_cap_32"],
  },
  {
    id: "dense_width_cap_8",
    treeId: "layer",
    name: "Dense幅 8",
    description: "Dense の幅を 1〜8 まで使えるようにする。",
    detail: "Dense の units を 1〜8 の整数から選べるようにする。",
    cost: 30,
    dependencies: ["dense_width_cap_6"],
  },
  {
    id: "dense_width_cap_10",
    treeId: "layer",
    name: "Dense幅 10",
    description: "Dense の幅を 1〜10 まで使えるようにする。",
    detail: "Dense の units を 1〜10 の整数から選べるようにする。",
    cost: 40,
    dependencies: ["dense_width_cap_8"],
  },
  {
    id: "model_params_cap_128",
    treeId: "layer",
    name: "総パラメータ上限 128",
    description: "モデル全体で 128 パラメータまで使えるようにする。",
    detail: "総パラメータ上限を 128 まで拡張する。",
    cost: 25,
    dependencies: ["model_params_cap_64"],
  },
  {
    id: "dense_width_cap_12",
    treeId: "layer",
    name: "Dense幅 12",
    description: "Dense の幅を 1〜12 まで使えるようにする。",
    detail: "Dense の units を 1〜12 の整数から選べるようにする。",
    cost: 50,
    dependencies: ["dense_width_cap_10"],
  },
  {
    id: "model_params_cap_256",
    treeId: "layer",
    name: "総パラメータ上限 256",
    description: "モデル全体で 256 パラメータまで使えるようにする。",
    detail: "総パラメータ上限を 256 まで拡張する。",
    cost: 40,
    dependencies: ["model_params_cap_128"],
  },
  {
    id: "model_params_cap_512",
    treeId: "layer",
    name: "総パラメータ上限 512",
    description: "モデル全体で 512 パラメータまで使えるようにする。",
    detail: "総パラメータ上限を 512 まで拡張する。",
    cost: 70,
    dependencies: ["model_params_cap_256"],
  },
  {
    id: "model_params_cap_1024",
    treeId: "layer",
    name: "総パラメータ上限 1,024",
    description: "モデル全体で 1,024 パラメータまで使えるようにする。",
    detail: "総パラメータ上限を 1,024 まで拡張する。",
    cost: 110,
    dependencies: ["model_params_cap_512"],
  },
  {
    id: "model_params_cap_4096",
    treeId: "layer",
    name: "総パラメータ上限 4,096",
    description: "モデル全体で 4,096 パラメータまで使えるようにする。",
    detail:
      "総パラメータ上限を 4,096 まで拡張する。画像ステージ向けの Conv2D + Flatten 構成も通しやすくなる。",
    cost: 180,
    dependencies: ["model_params_cap_1024"],
  },

  // ============ 活性化関数ツリー ============
  {
    id: "sigmoid",
    treeId: "activation",
    name: "Sigmoid",
    description: "出力を0〜1の範囲に変換する活性化関数。",
    detail: "どのような実数が入力されても、出力を必ず0～1の値で返すため、結果を確率として解釈できる。ただし入力の絶対値が大きいと深いネットワークでは学習が進みにくいことがある。ちなみに名前の由来はグラフにしたときの形がΣに似ていることにある。",
    cost: 0,
    dependencies: [],
  },
  {
    id: "relu",
    treeId: "activation",
    name: "ReLU",
    description: "負の値を0にする活性化関数。最も一般的。",
    detail: "入力値が0未満なら0を、0以上なら入力値を用いて処理をする。単純な関数なため計算が軽く、層を多く(深く)重ねても学習がきちんと進みやすい。",
    cost: 50,
    dependencies: ["sigmoid"],
  },
  {
    id: "gelu",
    treeId: "activation",
    name: "GELU",
    description: "Transformerで使われる滑らかな活性化関数。",
    detail: "入力の大きさに応じて値を滑らかに通す活性化関数。負の値も弱く残すため情報を失いにくく、深いネットワークでも学習が安定しやすい。Transformer などの高性能モデルで使われ、複雑なタスクで精度を伸ばしやすい。",
    cost: 120,
    dependencies: ["relu"],
  },

  // ============ 学習手法ツリー ============
  {
    id: "sgd",
    treeId: "optimizer",
    name: "SGD",
    description: "確率的勾配降下法。基本のオプティマイザ。",
    detail: "ニューラルネットワークによる予測値と正解値との誤差(損失)を減らす手法の一つ。ランダムに選んだ1つのデータで値を調整・更新する。学習率が大きいと誤差が最小となる点を通り過ぎ、小さいと収束までに時間がかかる。深いネットワークではReLu/GELUと組み合わせることが重要。",
    cost: 0,
    dependencies: [],
  },
  {
    id: "adam",
    treeId: "optimizer",
    name: "Adam",
    description: "適応的学習率を持つ高性能オプティマイザ。",
    detail: "損失を減らす手法の一つ。過去の更新の流れや値の変化量を参考にしながら、自動で調整しつつ重みを更新する。学習が安定しやすく、誤差が最小となる点に向かって進みやすい。深いネットワークや複雑なタスクで効果を発揮し、SGD よりも扱いやすいことが多い",
    cost: 120,
    dependencies: ["sgd"],
  },

  // ============ 正則化ツリー ============
  {
    id: "dropout",
    treeId: "regularization",
    name: "Dropout",
    description: "ランダムにノードを無効化して過学習を防ぐ。",
    detail: "学習中にランダムで一部のノードを使わないようにして、特定の部分に頼りすぎるのを防ぐ手法。使う場所が偏りにくくなるため、過学習を起こしやすいネットワークに向いている。一方で、小さなネットワークでは無効化しすぎて性能が落ちることがある。",
    cost: 120,
    dependencies: ["l2"],
  },
  {
    id: "l2",
    treeId: "regularization",
    name: "L2正則化",
    description: "重みの大きさにペナルティを課して過学習を防ぐ。",
    detail: "重みが極端に大きくならないように、全体を少しずつ弱める手法。重みが暴れにくくなり、安定した学習を続けたい構成に向いている。ただし、重要な特徴まで弱めてしまうことがあり、細かい調整が必要なタスクには不向きな場合がある。",
    cost: 90,
    dependencies: [],
  },
  {
    id: "l1",
    treeId: "regularization",
    name: "L1正則化",
    description: "重みをスパースにして特徴選択効果を持つ。",
    detail: "重みの中で重要でないものをほぼ 0 に近づけ、必要な部分だけを残す手法。特徴を選び取る力が強く、不要な情報を減らしてシンプルなモデルにしたいときに向いている。一方で、重みが急に 0 になりやすく、なめらかな調整が必要なタスクには向かない。",
    cost: 120,
    dependencies: ["l2"],
  },
];
