import type { SkillDef } from "../types";

/**
 * スキルマスターデータ。
 * treeId でスキルツリー画面上の4本のツリーに振り分けられる。
 * id は LayerNodeData.layerType / activation / regularization や
 * playStore.selectedOptimizer と直接対応する。
 */
export const SKILL_DATA: SkillDef[] = [
  // ============ 隠れ層ツリー ============
  {
    id: "dense",
    treeId: "layer",
    name: "全結合層 (Dense)",
    description: "基本的なニューラルネットワークの層。",
    detail: "Denseの詳細をここに書く",
    cost: 0,
    dependencies: [],
  },
  {
    id: "dense_width_cap_4",
    treeId: "layer",
    name: "Dense幅 4",
    description: "Dense の幅を 1〜4 まで使えるようにする。",
    detail: "Dense の units を 1〜4 の整数から選べるようにする。",
    cost: 10,
    dependencies: ["dense"],
  },
  {
    id: "model_params_cap_32",
    treeId: "layer",
    name: "総パラメータ上限 32",
    description: "モデル全体で 32 パラメータまで使えるようにする。",
    detail:
      "全層を合計した総パラメータ数の上限を 32 まで許可する。幅だけでなく、層を積んだときの総量も制御する。",
    cost: 0,
    dependencies: ["dense"],
  },
  {
    id: "conv2d",
    treeId: "layer",
    name: "畳み込み層 (Conv2D)",
    description: "空間的な特徴を抽出する層。画像系タスクに有効。",
    detail: "Conv2dの詳細をここに書く",
    cost: 180,
    dependencies: ["dense"],
  },
  {
    id: "flatten",
    treeId: "layer",
    name: "Flatten",
    description: "多次元テンソルを1次元に変換する層。",
    detail: "Flattenの詳細をここに書く",
    cost: 80,
    dependencies: ["conv2d"],
  },
  {
    id: "dense_width_cap_6",
    treeId: "layer",
    name: "Dense幅 6",
    description: "Dense の幅を 1〜6 まで使えるようにする。",
    detail: "Dense の units を 1〜6 の整数から選べるようにする。",
    cost: 20,
    dependencies: ["dense_width_cap_4"],
  },
  {
    id: "model_params_cap_64",
    treeId: "layer",
    name: "総パラメータ上限 64",
    description: "モデル全体で 64 パラメータまで使えるようにする。",
    detail: "総パラメータ上限を 64 まで拡張する。",
    cost: 15,
    dependencies: ["model_params_cap_32"],
  },
  {
    id: "dense_width_cap_8",
    treeId: "layer",
    name: "Dense幅 8",
    description: "Dense の幅を 1〜8 まで使えるようにする。",
    detail: "Dense の units を 1〜8 の整数から選べるようにする。",
    cost: 30,
    dependencies: ["dense_width_cap_6"],
  },
  {
    id: "model_params_cap_128",
    treeId: "layer",
    name: "総パラメータ上限 128",
    description: "モデル全体で 128 パラメータまで使えるようにする。",
    detail: "総パラメータ上限を 128 まで拡張する。",
    cost: 25,
    dependencies: ["model_params_cap_64"],
  },
  {
    id: "model_params_cap_256",
    treeId: "layer",
    name: "総パラメータ上限 256",
    description: "モデル全体で 256 パラメータまで使えるようにする。",
    detail: "総パラメータ上限を 256 まで拡張する。",
    cost: 40,
    dependencies: ["model_params_cap_128"],
  },
  {
    id: "model_params_cap_512",
    treeId: "layer",
    name: "総パラメータ上限 512",
    description: "モデル全体で 512 パラメータまで使えるようにする。",
    detail: "総パラメータ上限を 512 まで拡張する。",
    cost: 70,
    dependencies: ["model_params_cap_256"],
  },
  {
    id: "model_params_cap_1024",
    treeId: "layer",
    name: "総パラメータ上限 1,024",
    description: "モデル全体で 1,024 パラメータまで使えるようにする。",
    detail: "総パラメータ上限を 1,024 まで拡張する。",
    cost: 110,
    dependencies: ["model_params_cap_512"],
  },
  {
    id: "model_params_cap_4096",
    treeId: "layer",
    name: "総パラメータ上限 4,096",
    description: "モデル全体で 4,096 パラメータまで使えるようにする。",
    detail:
      "総パラメータ上限を 4,096 まで拡張する。画像ステージ向けの Conv2D + Flatten 構成も通しやすくなる。",
    cost: 180,
    dependencies: ["model_params_cap_1024"],
  },

  // ============ 活性化関数ツリー ============
  {
    id: "sigmoid",
    treeId: "activation",
    name: "Sigmoid",
    description: "出力を0〜1の範囲に変換する活性化関数。",
    detail: "Sigmoidの詳細をここに書く",
    cost: 0,
    dependencies: [],
  },
  {
    id: "relu",
    treeId: "activation",
    name: "ReLU",
    description: "負の値を0にする活性化関数。最も一般的。",
    detail: "Reluの詳細をここに書く",
    cost: 50,
    dependencies: ["sigmoid"],
  },
  {
    id: "gelu",
    treeId: "activation",
    name: "GELU",
    description: "Transformerで使われる滑らかな活性化関数。",
    detail: "GELUの詳細をここに書く",
    cost: 120,
    dependencies: ["relu"],
  },

  // ============ 学習手法ツリー ============
  {
    id: "sgd",
    treeId: "optimizer",
    name: "SGD",
    description: "確率的勾配降下法。基本のオプティマイザ。",
    detail: "SGDの詳細をここに書く",
    cost: 0,
    dependencies: [],
  },
  {
    id: "adam",
    treeId: "optimizer",
    name: "Adam",
    description: "適応的学習率を持つ高性能オプティマイザ。",
    detail: "Adamの詳細をここに書く",
    cost: 120,
    dependencies: ["sgd"],
  },

  // ============ 正則化ツリー ============
  {
    id: "dropout",
    treeId: "regularization",
    name: "Dropout",
    description: "ランダムにノードを無効化して過学習を防ぐ。",
    detail: "Dropoutの詳細をここに書く",
    cost: 120,
    dependencies: ["l2"],
  },
  {
    id: "l2",
    treeId: "regularization",
    name: "L2正則化",
    description: "重みの大きさにペナルティを課して過学習を防ぐ。",
    detail: "L2正則化の詳細をここに書く",
    cost: 90,
    dependencies: [],
  },
  {
    id: "l1",
    treeId: "regularization",
    name: "L1正則化",
    description: "重みをスパースにして特徴選択効果を持つ。",
    detail: "L1正則化の詳細をここに書く",
    cost: 120,
    dependencies: ["l2"],
  },
];
